package contenttype

type ContentType string

const (
	ApplicationJSON        = ContentType("application/json")
	ApplicationProto       = ContentType("application/proto")
	ApplicationMsgpack     = ContentType("application/msgpack")
	ApplicationForm        = ContentType("application/x-www-form-urlencoded")
	ApplicationOGG         = ContentType("application/ogg")
	ApplicationOctetStream = ContentType("application/octet-stream")
	ApplicationEDIX12      = ContentType("application/EDI-X12")
	ApplicationEDIFACT     = ContentType("application/EDIFACT")
	ApplicationXML         = ContentType("application/xml")
	ApplicationXMLDTD      = ContentType("application/xml-dtd")
	ApplicationXHTML       = ContentType("application/xhtml+xml")
	ApplicationXOP         = ContentType("application/xop+xml")
	ApplicationZip         = ContentType("application/zip")
	ApplicationGzip        = ContentType("application/gzip")
	Application7z          = ContentType("application/x-7z-compressed")
	ApplicationTar         = ContentType("application/x-tar")
	ApplicationBzip2       = ContentType("application/x-bzip2")
	ApplicationGzip2       = ContentType("application/x-gzip")
	ApplicationBzip        = ContentType("application/x-bzip")
	ApplicationXsltXML     = ContentType("application/xslt+xml")
	TextXML                = ContentType("text/xml")
	TextHTML               = ContentType("text/html")
	TextPlain              = ContentType("text/plain")
	TextCSS                = ContentType("text/css")
	TextCSV                = ContentType("text/csv")
	TextJavascript         = ContentType("text/javascript")
	MultipartRelated       = ContentType("multipart/related")
	MultipartForm          = ContentType("multipart/form-data")
	MultipartMixed         = ContentType("multipart/mixed")
	MultipartAlternative   = ContentType("multipart/alternative")
	ImageJPEG              = ContentType("image/jpeg")
	ApplicationMSword      = ContentType("application/msword")
	ApplicationPDF         = ContentType("application/pdf")
	ApplicationMSExcel     = ContentType("application/vnd.ms-excel")
)
